parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: test
    database_user: root
    database_password: mysql
    mailer_transport: "smtp"
    mailer_host: "localhost"
    mailer_user : ""
    mailer_password: ""
    mailer_encryption: "ssl"
    locale: es
    secret: 1a7e19bd4e680e3c5a80557e104b8d78d
    database_path: null