
BloggerBlogBundle_indexpage:
    pattern:  /
    defaults: { _controller: BloggerBlogBundle:Page:index }
# src/Blogger/BlogBundle/Resources/config/routing.yml
BloggerBlogBundle_homepage:
    pattern:  /jeje
    defaults: { _controller: BloggerBlogBundle:Page:index }
    requirements:
        _method:  GET

BloggerBlogBundle_about:
    pattern: /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
    requirements:
       _method:  GET

# src/blogger/blogBundle/Resources/config/routing.yml
BloggerBlogBundle_contact:
    pattern: /contact
    defaults: { _controller: BloggerBlogBundle:Page:contact}
    requirements:
        _method: GET|POST